version: "3.7"

services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/app/Dockerfile
    image: 2v2
    container_name: 2v2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=America/Santarem
    networks:
      2v2:
        ipv4_address: 172.16.14.4
  db:
    image: postgres:13-alpine
    ports:
      - "5014:5432"
    container_name: 2v2-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/data/2v2:/var/lib/postgresql/data
    networks:
      2v2:
        ipv4_address: 172.16.14.2

  nginx:
    image: nginx:alpine
    container_name: 2v2-nginx
    restart: unless-stopped
    ports:
      - "8014:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    environment:
      - TZ=America/Santarem
    networks:
      2v2:
        ipv4_address: 172.16.14.3

networks:
  2v2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.14.0/28
