version: "3.7"

services:
  app:
    build:
      args:
        user: marcio
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/app/Dockerfile
    image: solar
    container_name: solar-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=America/Santarem
    networks:
      solar:
        ipv4_address: 172.16.19.4
  db:
    image: postgres:13-alpine
    ports:
      - "5017:5432"
    container_name: solar-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/data/solar:/var/lib/postgresql/data
    networks:
      solar:
        ipv4_address: 172.16.19.2

  nginx:
    image: nginx:alpine
    container_name: solar-nginx
    restart: unless-stopped
    ports:
      - "8017:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    environment:
      - TZ=America/Santarem
    networks:
      solar:
        ipv4_address: 172.16.19.3

networks:
  solar:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.19.0/28
